In [1]:
X = rand (10,2)*100
y = rand (10,1)*1000
[m, n] = size(X);
X = [ones(m, 1) X];
theta = [-24; 0.2; 0.5];
X
theta

X =

   33.9889   14.1292
   59.3694    1.6811
    1.3600   99.4016
   69.7052   50.2520
    4.7767    7.2447
   19.0135   12.6510
   14.4128   26.7733
    4.5450   20.7203
   31.9460   86.0514
    1.7010   15.7090

y =

   944.8940
   559.5011
     5.9445
   529.2563
    76.0486
   164.4224
   119.9392
   253.8037
   936.9971
   491.9921

X =

    1.0000   33.9889   14.1292
    1.0000   59.3694    1.6811
    1.0000    1.3600   99.4016
    1.0000   69.7052   50.2520
    1.0000    4.7767    7.2447
    1.0000   19.0135   12.6510
    1.0000   14.4128   26.7733
    1.0000    4.5450   20.7203
    1.0000   31.9460   86.0514
    1.0000    1.7010   15.7090

theta =

  -24.00000
    0.20000
    0.50000



In [2]:
z=X*theta

z =

  -10.1376
  -11.2855
   25.9728
   15.0670
  -19.4223
  -13.8718
   -7.7308
  -12.7309
   25.4149
  -15.8053



In [3]:
sigmoid(z);

g =

   0.0000395612847
   0.0000125530157
   0.9999999999947
   0.9999997139310
   0.0000000036729
   0.0000009452536
   0.0004389013265
   0.0000029583828
   0.9999999999908
   0.0000001367249



In [4]:
J=  (-y' * log(sigmoid(z)) - (1 - y)' * log(1- sigmoid(z)))/m;

g =

   0.0000395612847
   0.0000125530157
   0.9999999999947
   0.9999997139310
   0.0000000036729
   0.0000009452536
   0.0004389013265
   0.0000029583828
   0.9999999999908
   0.0000001367249

g =

   0.0000395612847
   0.0000125530157
   0.9999999999947
   0.9999997139310
   0.0000000036729
   0.0000009452536
   0.0004389013265
   0.0000029583828
   0.9999999999908
   0.0000001367249



In [5]:
h_theta = sigmoid(X * theta); % X: m * n theta: n * 1 h_theta: m * 1

J = (-y' * log(h_theta) - (1 - y)' * log(1 - h_theta)) / m; % y: m * 1

g =

   0.0000395612847
   0.0000125530157
   0.9999999999947
   0.9999997139310
   0.0000000036729
   0.0000009452536
   0.0004389013265
   0.0000029583828
   0.9999999999908
   0.0000001367249



In [6]:
grad = zeros(size(theta));
lambda=5

z= X * theta
J= (-y' * log(sigmoid(z)) - (1 - y)' * log(1- sigmoid(z)))/m ...
    + (theta'*theta) * lambda/(2*m)

grad(1) = (X(1)' * (sigmoid(z) - y))/m
for g=2:size(theta)
  grad(g) = (X(g)' * (sigmoid(z) - y))/m + (lambda/m) * theta(g)
  
endfor

lambda =  5
z =

  -10.1376
  -11.2855
   25.9728
   15.0670
  -19.4223
  -13.8718
   -7.7308
  -12.7309
   25.4149
  -15.8053

g =

   0.0000395612847
   0.0000125530157
   0.9999999999947
   0.9999997139310
   0.0000000036729
   0.0000009452536
   0.0004389013265
   0.0000029583828
   0.9999999999908
   0.0000001367249

g =

   0.0000395612847
   0.0000125530157
   0.9999999999947
   0.9999997139310
   0.0000000036729
   0.0000009452536
   0.0004389013265
   0.0000029583828
   0.9999999999908
   0.0000001367249

J =  115.04
g =

   0.0000395612847
   0.0000125530157
   0.9999999999947
   0.9999997139310
   0.0000000036729
   0.0000009452536
   0.0004389013265
   0.0000029583828
   0.9999999999908
   0.0000001367249

error: =: nonconformant arguments (op1 is 1x1, op2 is 10x1)
g =

   0.0000395612847
   0.0000125530157
   0.9999999999947
   0.9999997139310
   0.0000000036729
   0.0000009452536
   0.0004389013265
   0.0000029583828
   0.9999999999908
   0.0000001367249

error: =: noncon

In [7]:
(X(1)' * (sigmoid(z) - y))/m

g =

   0.0000395612847
   0.0000125530157
   0.9999999999947
   0.9999997139310
   0.0000000036729
   0.0000009452536
   0.0004389013265
   0.0000029583828
   0.9999999999908
   0.0000001367249

ans =

  -94.48940
  -55.95011
   -0.49445
  -52.82563
   -7.60486
  -16.44224
  -11.99387
  -25.38037
  -93.59971
  -49.19921



In [8]:
theta'*theta

ans =  576.29


In [9]:
theta

theta =

  -24.00000
    0.20000
    0.50000



In [10]:
theta(2:)

parse error:

  syntax error

>>> theta(2:)
            ^



In [11]:
theta_reg = theta
theta_reg(1) = []
theta_reg(1)

theta_reg =

  -24.00000
    0.20000
    0.50000

theta_reg =

   0.20000
   0.50000

ans =  0.20000


In [12]:
theta

theta =

  -24.00000
    0.20000
    0.50000



In [13]:
X'*sigmoid(z)
sigmoid(z)'*X

g =

   0.0000395612847
   0.0000125530157
   0.9999999999947
   0.9999997139310
   0.0000000036729
   0.0000009452536
   0.0004389013265
   0.0000029583828
   0.9999999999908
   0.0000001367249

ans =

     3.0005
   103.0196
   235.7174

g =

   0.0000395612847
   0.0000125530157
   0.9999999999947
   0.9999997139310
   0.0000000036729
   0.0000009452536
   0.0004389013265
   0.0000029583828
   0.9999999999908
   0.0000001367249

ans =

     3.0005   103.0196   235.7174



In [14]:
X

X =

    1.0000   33.9889   14.1292
    1.0000   59.3694    1.6811
    1.0000    1.3600   99.4016
    1.0000   69.7052   50.2520
    1.0000    4.7767    7.2447
    1.0000   19.0135   12.6510
    1.0000   14.4128   26.7733
    1.0000    4.5450   20.7203
    1.0000   31.9460   86.0514
    1.0000    1.7010   15.7090



In [1]:
a = 1:10; % Create a and b
b = 3;
a == b % You should try different values of b here

ans =

  0  0  1  0  0  0  0  0  0  0



In [2]:
b

b =  3


In [3]:
a

a =

    1    2    3    4    5    6    7    8    9   10

