In [5]:
%% Setup the parameters you will use for this exercise
input_layer_size  = 400;  % 20x20 Input Images of Digits
hidden_layer_size = 25;   % 25 hidden units
num_labels = 10;          % 10 labels, from 1 to 10   
                          % (note that we have mapped "0" to label 10)

X=randi(100,500,400)

m = size(X, 1);

Theta1=randi(100,25,400)
Theta2=randi(100,10,25)


nn_params = [Theta1(:) ; Theta2(:)];

lambda = 0;



% Setup some useful variables
m = size(X, 1);
         
% You need to return the following variables correctly 
J = 0;
Theta1_grad = zeros(size(Theta1));
Theta2_grad = zeros(size(Theta2));

% ====================== YOUR CODE HERE ======================
% Instructions: You should complete the code by working through the
%               following parts.
%
% Part 1: Feedforward the neural network and return the cost in the
%         variable J. After implementing Part 1, you can verify that your
%         cost function computation is correct by verifying the cost
%         computed in ex4.m
%
% Part 2: Implement the backpropagation algorithm to compute the gradients
%         Theta1_grad and Theta2_grad. You should return the partial derivatives of
%         the cost function with respect to Theta1 and Theta2 in Theta1_grad and
%         Theta2_grad, respectively. After implementing Part 2, you can check
%         that your implementation is correct by running checkNNGradients
%
%         Note: The vector y passed into the function is a vector of labels
%               containing values from 1..K. You need to map this vector into a 
%               binary vector of 1's and 0's to be used with the neural network
%               cost function.
%
%         Hint: We recommend implementing backpropagation using a for-loop
%               over the training examples if you are implementing it for the 
%               first time.
%
% Part 3: Implement regularization with the cost function and gradients.
%
%         Hint: You can implement this around the code for
%               backpropagation. That is, you can compute the gradients for
%               the regularization separately and then add them to Theta1_grad
%               and Theta2_grad from Part 2.
%




X =

 Columns 1 through 13:

    37    63    67    96    60    11    68    60    78    10     5    65     1
    21    43    34    65    38    62    38    96    22    67    95    99    63
    52    36    73    34    37    59    62    66    29    35    90    73    12
    82    14    78    12    25    41    10    98    99    89    41    83    68
    55    77    62    99    36    80    31    20    15    68    28    53    20
    97     7    33    25    25    56    94    56    78    34    48    83    30
    97    60    62    32    19    54    13    55    71    48    55    50    67
    21    75    34     5    48    17    28    42     9    43    17    80    18
   100    36    27    59     8    36    90    35    75    87    34     6    82
    28    44    80    29    85    36    87    58    89    73    45     4    11
    17    50    54    89    16    59    41    78    24    13    79    67     2
    69    87    15    32    17    85    51    76    66    91    81    43     5
    37    76    15    2

Theta1 =

 Columns 1 through 13:

    20    49    95    74     9    99    81    75    29    65    80    42     7
    19    95    60    88    64    65    88    17    31    33    91     2    49
    45    77    14     5    15    38    91     7    92    70    97    46     3
    97    24    25    31    96    67    85    84    53    70    92     7    35
    20    77    59    87    57    30    72    39    49    44    25    14    39
    57    42    13    68    77    46    67    40    51    60    52    41    33
    32    93     8    98    44    25    88    36    10    56    75    45    23
     4     1    52    92    17     5    38    90    96    33    12    67    85
    55    35    20    14    51    89     1     1    32    31    76    71    31
    59    43    18    33    95    64    76    77    20    65    85    73    20
    22    12    50    94    94    71    65    60    20    37     5     7    71
    44    99    26    41    66    59    17    59     7    45    77    30    50
    87     8    81

Theta2 =

 Columns 1 through 13:

    13    20    58    27    65    85    35    50    78    71    44    80    55
    20    38    80    31    35    87     2    98    12    17    75    98    37
    89     9    70    21    63    99    42     9    12    94    28    30    97
    54    46    93    47    61    59    65    42    15    24    24    26    83
    10    91    37    78    55    47    16    42    70    50    58    83    93
    86    17    25    63    20    95    70    77    14    62    25    36    98
    54    80    71    28    88    71    63    22    13    35    25    46    39
     8    21     8    26    93     7    87    17    64    79    83    36    27
    10    48     5    53    81    22    69    48    47     4    77    70    70
    69    74    31    45    60    14    22    15    94    87    26    13    29

 Columns 14 through 25:

    19    48    82     5     7    79    56    29    16    28    56    62
    98    76    80    89     6     8    58    72    95     8    41    34
    

In [14]:
X=randi(10,3,2)
b=-X.*log(0.3)
c=(1-X).*log(1-0.3)
bmc=b-c
a=sum(bmc)
Y=sum(a);

X =

    1    5
   10    5
   10    9

b =

    1.2040    6.0199
   12.0397    6.0199
   12.0397   10.8358

c =

  -0.00000   1.42670
   3.21007   1.42670
   3.21007   2.85340

bmc =

   1.2040   4.5932
   8.8297   4.5932
   8.8297   7.9824

a =

   18.863   17.169



In [21]:
y=randi(10,20,1)

Y = zeros(20, 10);

y =

    4
    9
   10
    7
    2
    1
    2
    4
    7
    9
   10
    3
    7
    8
   10
    2
    9
    6
    1
    5



In [22]:
for i = 1: 10
    Y(:, i) = (y == i);
end

In [23]:
Y

Y =

   0   0   0   1   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   0   0   0   1
   0   0   0   0   0   0   1   0   0   0
   0   1   0   0   0   0   0   0   0   0
   1   0   0   0   0   0   0   0   0   0
   0   1   0   0   0   0   0   0   0   0
   0   0   0   1   0   0   0   0   0   0
   0   0   0   0   0   0   1   0   0   0
   0   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   0   0   0   0   1
   0   0   1   0   0   0   0   0   0   0
   0   0   0   0   0   0   1   0   0   0
   0   0   0   0   0   0   0   1   0   0
   0   0   0   0   0   0   0   0   0   1
   0   1   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   1   0
   0   0   0   0   0   1   0   0   0   0
   1   0   0   0   0   0   0   0   0   0
   0   0   0   0   1   0   0   0   0   0



In [ ]:
a1 = [ones(m, 1) X];% 5000 * 401
a1

** Warning: Cannot interrupt Octave on Windows


In [ ]:
z2 = a1 * Theta1';% 5000 * 25
a2 = [ones(size (z2,1),1) sigmoid(z2)]; %5000 * (25 + 1)
z3 = a2 * Theta2';% 5000 * 10
a3 = sigmoid(z3);
h = a3;

Y = zeros(m, num_labels);
for i = 1: num_labels
    Y(:, i) = (y == i);
end
J = 1/m * sum(sum(-Y.*log(h)-(1-Y).*log(1-h)));
J = J + lambda/2/m *(sum(sum(Theta1(:, 2: end).^2)) + sum(sum(Theta2(:, 2: end).^2)));

delta3 = zeros(m, num_labels);
for k = 1:num_labels
    delta3(:, k) = a3(:, k)-(y == k);% 5000 * 10
end
delta2 = delta3 * Theta2.*[ones(size (z2,1), 1) sigmoidGradient(z2)];% 5000 * 26


Delta1 = delta2(:, 2: end)'* a1;% 25 * 401
Delta2 = delta3'* a2;


Theta1_grad = 1/m * Delta1;
Theta2_grad = 1/m * Delta2;

reg1 = lambda/m * Theta1;
reg2 = lambda/m * Theta2;
reg1 (:, 1) = 0;
reg2 (:, 1) = 0;
Theta1_grad = Theta1_grad + reg1;
Theta2_grad = Theta2_grad + reg2;


grad = [Theta1_grad(:); Theta2_grad(:)];


end